### ISSUE TITLE
[feature request] geyser support

### ISSUE THREAD

**Issue by TOWUK** [YouHaveTrouble/ChitChat#1]
please add true/false toggle verify message mojang api
![image](https://github.com/YouHaveTrouble/ChitChat/assets/28830162/9b0e89e0-0621-418e-aeaa-8adb7dbf07cd)
![image](https://github.com/YouHaveTrouble/ChitChat/assets/28830162/408b21c8-a284-44af-b103-cebb8d153479)

**Comment by YouHaveTrouble** [comment]
it will literally make most of the plugin useless due to the lack of the signatures used to delete messages.

**Comment by YouHaveTrouble** [comment]
To clarify more: Basic stuff like chat formatting should still work fine. You won't be able to delete messages without message signatures enabled, because it's literally what's required to send to the client to make it remove the message. It's technically not possible without it.
