### ISSUE TITLE
"This version of Minecraft is unsupported: 1.20.4"

### ISSUE THREAD

**Issue by EmanYm** [YouHaveTrouble/ChitChat#2]
Apex Hosted server
Purpur 1.20.4-build 2111
Java 17.0.9

ChitChat 1.1
Spark 1.10.58

[mclogs](https://mclo.gs/FqKec8A#L34)

**Comment by YouHaveTrouble** [comment]
fixed in 1.1.1

**Comment by EmanYm** [comment]
Thank you!
